name: buscando_farmacias_chilenas
description: "Una aplicación Flutter para buscar farmacias en Chile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Dependencias para persistencia de datos
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  http: ^1.2.1
  path: ^1.8.0

  # Dependencia para íconos atractivos
  font_awesome_flutter: ^10.1.0

  # Dependencia para fuentes atractivas
  google_fonts: ^4.0.3

  # Dependencia para abrir URLs
  url_launcher: ^6.1.7
  share: ^2.0.4
  
  # Dependencia para geocoding
  geocoding: ^3.0.0

  # Dependencia para la geolocalización
  geolocator: ^9.0.2

  # Dependencia para splash screen
  flutter_native_splash: ^2.0.5+1
  
  # Dependencia para audio
  audioplayers: ^6.0.0
  flutter_sound: ^9.0.9
  flutter_sound_platform_interface: ^9.0.9
  flutter_sound_web: ^9.0.9

  # Dependencia para el logger
  logger: ^1.1.0  

  # Dependencia para cambiar el nombre del paquete de la aplicación
  change_app_package_name: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ministerio.png
    - assets/music/musica_fondo.mp3

flutter_native_splash:
  color: "#ffffff"
  image: assets/ministerio.png
  android: true
  ios: true
  web: false
